/* Generated with cbindgen:0.13.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

struct xyz {
    uint32_t x;
    uint32_t y;
    float z;
};

extern "C" {

void parse_float_data(const float *ptr, uint32_t length);

void parse_xyz_data(const xyz *ptr, uint32_t length);

void process_rgb_image_rs(const uint8_t *ptr, uint32_t width, uint32_t height);

void write_small_image_rs();

} // extern "C"
